schemas:
  Product:
    type: object
    required:
      - id
      - name
      - description
      - price
      - category
      - createdAt
      - updatedAt
      - isFavorite
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      price:
        type: number
      category:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      isFavorite:
        type: boolean
  ProductsList:
    type: object
    required:
      - list
      - total
      - totalPages
    properties:
      list:
        type: array
        items:
          $ref: '#/schemas/Product'
      total:
        type: integer
      totalPages:
        type: integer

getAllProducts:
  summary: Get all products for current user
  parameters:
    - name: page
      in: query
      required: false
      schema:
        type: integer
        default: 1
    - name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 10
  responses:
    '200':
      description: A list of products
      content:
        application/json:
          schema:
            $ref: '#/schemas/ProductsList'